tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "samuelmeuli/tap" # for excluding from Time Machine
brew "dark-mode" # CLI to toggle dark mode
brew "deno"
brew "diff-so-fancy"
brew "exiftool"
brew "gh"
brew "git"
brew "gradle"
brew "grep"
brew "ldns"
brew "libfido2"
brew "mas"
brew "mysql"
brew "node"
brew "nvm"
brew "openssh"
brew "openssl@3"
brew "python@3.8"
brew "ruby"
brew "vim"
brew "webp"
brew "yarn"
brew "zsh"
brew "zsh-completions"
cask "docker"
cask "firefox-developer-edition"
cask "flycut"
cask "font-fira-code"
cask "gimp"
cask "github"
cask "google-chrome"
cask "google-chrome-dev"
cask "obsidian"
cask "postman"
cask "rectangle"
cask "rescuetime"
cask "slack"
cask "virtualbox"
cask "visual-studio-code"
cask "vnc-viewer"
mas "Brother iPrint&Scan", id: 1193539993
# mas "GarageBand", id: 682658836
# mas "iMovie", id: 408981434
# mas "Numbers", id: 409203825
# mas "Photos Duplicate Cleaner", id: 592704001
mas "Speedtest", id: 1153157709
vscode "bungcip.better-toml"
vscode "dawhite.mustache"
vscode "eamodio.gitlens"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "GitHub.vscode-pull-request-github"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vsliveshare.vsliveshare"
vscode "Orta.vscode-jest"
vscode "redhat.java"
vscode "ronnidc.nunjucks"
vscode "ryu1kn.partial-diff"
vscode "sissel.shopify-liquid"
vscode "streetsidesoftware.code-spell-checker"
vscode "travisthetechie.write-good-linter"
vscode "VisualStudioExptTeam.intellicode-api-usage-examples"
vscode "VisualStudioExptTeam.vscodeintellicode"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscodevim.vim"
vscode "WallabyJs.quokka-vscode"
vscode "znck.grammarly"
